version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
chat:
  image: silvesda/chatterv2.0 
  restart: always
  ports:
    -9900:3000
  environment:
    -REDIS_HOST=redis
    -REDIS_PORT=6379

