version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

apiVersion: v1
kind: Config
clusters:
- name: "teko-kubernetes"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT0RFNU1UQXlPVFF3SGhjTk1qTXdOREU1TVRNeE9ERTBXaGNOTXpNd05ERTJNVE14T0RFMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT0RFNU1UQXlPVFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFST1NhN215Sk9McHE1Nkh1YXdlYStVN3RwSVRTZVJ1U1RFMUd4SnFQQjkKOGthVnFkZ0k5OXVBUDZ3ZmxlRlExN0pTc0FOS3Y5UzdVSTZkdll0RFVNYU1vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVFhNkpBSUlOdUQvQUw2UGI5cmRCCnBXYWQvZFV3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUpjWFh0M1BqbEJGUjJrWGxIMFkvOElFd004dGtJd3MKR1UwT0oxVExQRElkQWlFQXVvaU5TbjN6T1ZiSmg0eFBiYUlUcDcvNTNFYThFTkRJekhmM05lMSt6L2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: "https://webhost.internet-box.ch:6443"
contexts:
- name: "silvestri-teko11@teko-kubernetes"
  context:
    cluster: "teko-kubernetes"
    namespace: "teko11"
    user: "silvestri"
users:
- name: "silvestri"
  user:
    token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IlMyd2NqVVJjeTRqWnY3RmZOUlpHTHNUTDl0NTdaSDNabGllLXJNNWgwSk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0ZWtvMTEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic2lsdmVzdHJpLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InNpbHZlc3RyaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImMxODk2MDU1LTgxNmUtNGVkNC1hNjU4LTc3ZTJjNTIxMzJhOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp0ZWtvMTE6c2lsdmVzdHJpIn0.AnPJn5gSDRv1i8Myz5JPUjjx3jLrIFp2915_Y2kOxfwvsDIamRThRVJP7ZFYKW04BaWRq1QtmVqUbQIkqAgTiMPZfv4rQPQmaD8ULs1CzVWBr2s5ZEDo0LhEOMESb7pZv-Co5KXuM9WSaBwLwifWVTNBYjiS0eBGlrhF20kiiaz-abnJlYUrFrPwufA8_p8dp-dsg6ivQ7vnff3q7BAGEqvzYtHzLi853DU6rQh5FvEIHnqzf_YmFxF3cppCm5sxynzUeKtgc7bZLaudy9VLWv-LzAfZblXwHDb3O4GPThc4rIwr9e-VkQHLyZiflDzX8dVKVqBTusJpq28LKXO7Yw"
current-context: "silvestri-teko11@teko-kubernetes"