apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: teko11 # Replace with your namespace
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
